// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 3. 31. 오후 12:12:58
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Developments/interiro-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developments/interiro-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developments/interiro-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developments/interiro-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developments/interiro-website/plugins/**/*.{js,ts,mjs}","D:/Developments/interiro-website/composables/**/*.{js,ts,mjs}","D:/Developments/interiro-website/utils/**/*.{js,ts,mjs}","D:/Developments/interiro-website/pages/index.vue","D:/Developments/interiro-website/pages/aiease.vue","D:/Developments/interiro-website/pages/home-3.vue","D:/Developments/interiro-website/pages/sample.vue","D:/Developments/interiro-website/pages/company.vue","D:/Developments/interiro-website/pages/contact.vue","D:/Developments/interiro-website/pages/service.vue","D:/Developments/interiro-website/pages/bg-remove.vue","D:/Developments/interiro-website/pages/portfolio.vue","D:/Developments/interiro-website/pages/admin/index.vue","D:/Developments/interiro-website/pages/aiease-clone.vue","D:/Developments/interiro-website/pages/project/[id].vue","D:/Developments/interiro-website/pages/removebg-clone.vue","D:/Developments/interiro-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Developments/interiro-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Developments/interiro-website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;