// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 3. 31. 오전 1:04:43
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Development/interiro_website/developments/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/interiro_website/developments/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/interiro_website/developments/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/interiro_website/developments/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/interiro_website/developments/plugins/**/*.{js,ts,mjs}","D:/Development/interiro_website/developments/composables/**/*.{js,ts,mjs}","D:/Development/interiro_website/developments/utils/**/*.{js,ts,mjs}","D:/Development/interiro_website/developments/pages/index.vue","D:/Development/interiro_website/developments/pages/sample.vue","D:/Development/interiro_website/developments/pages/company.vue","D:/Development/interiro_website/developments/pages/contact.vue","D:/Development/interiro_website/developments/pages/service.vue","D:/Development/interiro_website/developments/pages/portfolio.vue","D:/Development/interiro_website/developments/pages/admin/index.vue","D:/Development/interiro_website/developments/pages/project/[id].vue","D:/Development/interiro_website/developments/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Development/interiro_website/developments/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Development/interiro_website/developments/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;